---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  roles:
    - role: ansible-system_journald

  vars:
    journald_config:
      ForwardToSyslog: "yes"
    journald_wipe_persistent: true
