---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  vars:
    journald_config:
      ForwardToSyslog: "yes"
    journald_wipe_persistent: true

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-system_journald
